# Generated by Django 2.2.9 on 2020-04-03 13:40

import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('descr', models.TextField(blank=True, null=True)),
                ('img', models.CharField(blank=True, max_length=512, null=True)),
                ('rating', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('complexity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('length', models.FloatField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
            ],
        ),
        migrations.AlterField(
            model_name='reserves',
            name='descr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reserves',
            name='img',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='reserves',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
