# Generated by Django 2.2.9 on 2020-04-03 14:28

import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200403_1340'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('descr', models.TextField(blank=True, null=True)),
                ('img', models.CharField(blank=True, max_length=512, null=True)),
                ('rating', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('route_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sights', to='api.Routes', verbose_name='Маршрут')),
            ],
        ),
    ]
