# Generated by Django 2.2.9 on 2020-04-03 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200403_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='raiting',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='RouteReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('img', models.ImageField(upload_to='')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default='5', verbose_name='Рейтинг')),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RouteReview', to='api.Reserves', verbose_name='Маршрут')),
            ],
            options={
                'verbose_name': 'Отзыв о маршруте',
                'verbose_name_plural': 'Отзывы о маршрутах',
            },
        ),
        migrations.CreateModel(
            name='ReserveReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('img', models.ImageField(upload_to='')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default='5', verbose_name='Рейтинг')),
                ('reserve', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ReserveReview', to='api.Reserves', verbose_name='Заповедник')),
            ],
            options={
                'verbose_name': 'Отзыв о заповеднинке',
                'verbose_name_plural': 'Отзывы о заповеднинках',
            },
        ),
    ]
