# Generated by Django 2.2.9 on 2020-04-03 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200403_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='known_routes',
            field=models.ManyToManyField(to='api.Routes'),
        ),
    ]
