# Generated by Django 2.2.9 on 2020-04-03 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_userprofile_known_routes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
