# Generated by Django 2.2.9 on 2020-04-04 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200404_0019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewspictures',
            options={'verbose_name': 'Картинка', 'verbose_name_plural': 'Картинки'},
        ),
        migrations.RemoveField(
            model_name='routereview',
            name='img',
        ),
    ]
