# Generated by Django 2.2.9 on 2020-04-04 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200404_0135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservereview',
            name='img',
        ),
    ]
