# Generated by Django 2.2.9 on 2020-04-04 08:52

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_reservereview_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('img', models.CharField(blank=True, max_length=512, null=True)),
                ('goal', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Дсотижение',
                'verbose_name_plural': 'Дсотижения',
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='achievements',
            field=models.ManyToManyField(to='api.Achievements'),
        ),
    ]
