# Generated by Django 2.2.9 on 2020-04-04 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20200404_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserves',
            name='pictures',
            field=models.ManyToManyField(to='api.ReviewsPictures'),
        ),
        migrations.AddField(
            model_name='routes',
            name='reserve',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Route', to='api.Reserves', verbose_name='Заповедник'),
        ),
    ]
