# Generated by Django 2.2.9 on 2020-04-04 11:46

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20200404_1113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserves',
            name='img',
        ),
        migrations.RemoveField(
            model_name='routes',
            name='img',
        ),
        migrations.AlterField(
            model_name='reserves',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
        ),
    ]
