# Generated by Django 2.2.9 on 2020-04-04 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20200404_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservereview',
            name='pictures',
            field=models.ManyToManyField(blank=True, to='api.ReviewsPictures'),
        ),
        migrations.AlterField(
            model_name='reserves',
            name='pictures',
            field=models.ManyToManyField(related_name='picture_url', to='api.ReviewsPictures'),
        ),
        migrations.AlterField(
            model_name='routereview',
            name='pictures',
            field=models.ManyToManyField(blank=True, to='api.ReviewsPictures'),
        ),
    ]
