# Generated by Django 2.2.9 on 2020-04-04 20:13

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20200404_1649'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievements',
            options={'verbose_name': 'Доcтижение', 'verbose_name_plural': 'Доcтижения'},
        ),
        migrations.RemoveField(
            model_name='routes',
            name='descr',
        ),
        migrations.RemoveField(
            model_name='sights',
            name='route_fk',
        ),
        migrations.AddField(
            model_name='sights',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sights',
            name='reserve',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SightReserve', to='api.Reserves', verbose_name='Заповедник'),
        ),
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('goal', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('group', models.ManyToManyField(blank=True, to='api.userProfile')),
                ('guide', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='GuideAccount', to='api.Reserves', verbose_name='Гид')),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TripRoute', to='api.Reserves', verbose_name='Маршрут')),
            ],
            options={
                'verbose_name': 'Доcтижение',
                'verbose_name_plural': 'Доcтижения',
            },
        ),
    ]
