# Generated by Django 2.2.9 on 2020-04-04 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20200404_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sights',
            name='done',
        ),
    ]
