# Generated by Django 2.2.9 on 2020-04-04 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_sights_done'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trips',
            options={'verbose_name': 'Поход', 'verbose_name_plural': 'Походы'},
        ),
        migrations.AlterField(
            model_name='trips',
            name='guide',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='GuideAccount', to='api.userProfile', verbose_name='Гид'),
        ),
    ]
