# Generated by Django 2.2.9 on 2020-04-05 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20200405_0005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trips',
            name='goal',
        ),
    ]
