# Generated by Django 2.2.9 on 2020-04-05 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_trips_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trips',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TripRoute', to='api.Routes', verbose_name='Маршрут'),
        ),
    ]
