# Generated by Django 2.2.9 on 2020-04-05 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20200405_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='trips',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
