# Generated by Django 2.2.9 on 2020-04-05 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_trips_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='trips',
            name='reserve',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TripReserve', to='api.Reserves', verbose_name='Заповедник'),
        ),
    ]
