# Generated by Django 2.2.9 on 2020-04-05 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_trips_reserve'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='geocash',
            options={'verbose_name': 'Геокэшинг', 'verbose_name_plural': 'Геокэшинг'},
        ),
        migrations.RemoveField(
            model_name='geocash',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='geocash',
            name='img',
            field=models.ImageField(blank=True, default=None, upload_to='picture'),
            preserve_default=False,
        ),
    ]
