# Generated by Django 2.2.9 on 2020-04-05 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20200405_0922'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sights',
            options={'verbose_name': 'Геокэшинг', 'verbose_name_plural': 'Геокэшинг'},
        ),
        migrations.DeleteModel(
            name='GeoCash',
        ),
    ]
